export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export JAVA_HOME=$(/usr/libexec/java_home)
export SCALA_HOME='/usr/local/scala'
export CLASSPATH="/usr/local/Cellar/antlr/4.2/antlr-4.2-complete.jar:$CLASSPATH"
alias grun='java org.antlr.v4.runtime.misc.TestRig'
alias vim='/usr/local/Cellar/vim/7.4.253/bin/vim'
alias vi='vim'
alias emacs='/usr/local/Cellar/emacs/24.3/bin/emacs'
